version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
    command: /opt/mssql/bin/sqlservr

  aecclima:
    build:
      context: .
      dockerfile: Dockerfile
    image: aecclima-aecclima
    ports:
      - "5062:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WeatherDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    command: /bin/sh -c "./wait-for-it.sh sqlserver:1433 -- dotnet ef database update --context AppDbContext -p AeCClima/AeCClima.csproj -s AeCClima/AeCClima.csproj && dotnet AeCClima.dll"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver

volumes:
  sqlserverdata:
